name: CI

on:
  push:
    branches:
      - dev
      - master

env:
  PYTHON_VERSION: 3.9

jobs:
  multi_arch_build:
    runs-on: ubuntu-latest
    name: Image Build
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      - name: Create version file
        run: make version
      - name: Create short sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Build dev container and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          target: devcontainer
          tags: |
            ${{secrets.DOCKER_USER}}/frigate:${{ github.ref_name }}-${{ env.SHORT_SHA }}-devcontainer
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build dev container trt and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          target: devcontainer-trt
          tags: |
            ${{secrets.DOCKER_USER}}/frigate:${{ github.ref_name }}-${{ env.SHORT_SHA }}-devcontainer-trt
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          target: frigate
          tags: |
            ${{secrets.DOCKER_USER}}/frigate:${{ github.ref_name }}-${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push TensorRT
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          target: frigate-tensorrt
          tags: |
            ${{secrets.DOCKER_USER}}/frigate:${{ github.ref_name }}-${{ env.SHORT_SHA }}-tensorrt
          cache-from: type=gha
